

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarBrand',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('brand', models.CharField(max_length=100, unique=True, verbose_name='汽车品牌名称')),
                ('brand_img', models.URLField(max_length=255, verbose_name='品牌图标链接')),
                ('brand_id', models.CharField(blank=True, max_length=50, verbose_name='品牌ID')),
            ],
            options={
                'verbose_name': '汽车品牌',
                'verbose_name_plural': '汽车品牌',
            },
        ),
        migrations.CreateModel(
            name='CarInformationBeijing',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('brand', models.CharField(max_length=100, verbose_name='品牌')),
                ('carname', models.CharField(max_length=100, verbose_name='汽车名称')),
                ('carimg', models.URLField(max_length=255, verbose_name='汽车图片链接')),
                ('salevolume', models.IntegerField(verbose_name='销售量')),
                ('price', models.CharField(max_length=100, verbose_name='价格')),
                ('manufacturer', models.CharField(max_length=100, verbose_name='制造商')),
                ('carmodel', models.CharField(max_length=50, verbose_name='车型')),
                ('energytype', models.CharField(max_length=50, verbose_name='能源类型')),
                ('marketime', models.CharField(max_length=50, verbose_name='上市时间')),
                ('insure', models.CharField(blank=True, max_length=100, verbose_name='保修信息')),
            ],
            options={
                'verbose_name': '汽车信息',
                'verbose_name_plural': '汽车信息',
                'unique_together': {('brand', 'carname')},
            },
        ),
        migrations.CreateModel(
            name='CarInformationChengdu',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('brand', models.CharField(max_length=100, verbose_name='品牌')),
                ('carname', models.CharField(max_length=100, verbose_name='汽车名称')),
                ('carimg', models.URLField(max_length=255, verbose_name='汽车图片链接')),
                ('salevolume', models.IntegerField(verbose_name='销售量')),
                ('price', models.CharField(max_length=100, verbose_name='价格')),
                ('manufacturer', models.CharField(max_length=100, verbose_name='制造商')),
                ('carmodel', models.CharField(max_length=50, verbose_name='车型')),
                ('energytype', models.CharField(max_length=50, verbose_name='能源类型')),
                ('marketime', models.CharField(max_length=50, verbose_name='上市时间')),
                ('insure', models.CharField(blank=True, max_length=100, verbose_name='保修信息')),
            ],
            options={
                'verbose_name': '汽车信息',
                'verbose_name_plural': '汽车信息',
                'unique_together': {('brand', 'carname')},
            },
        ),
        migrations.CreateModel(
            name='CarInformationChongqing',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('brand', models.CharField(max_length=100, verbose_name='品牌')),
                ('carname', models.CharField(max_length=100, verbose_name='汽车名称')),
                ('carimg', models.URLField(max_length=255, verbose_name='汽车图片链接')),
                ('salevolume', models.IntegerField(verbose_name='销售量')),
                ('price', models.CharField(max_length=100, verbose_name='价格')),
                ('manufacturer', models.CharField(max_length=100, verbose_name='制造商')),
                ('carmodel', models.CharField(max_length=50, verbose_name='车型')),
                ('energytype', models.CharField(max_length=50, verbose_name='能源类型')),
                ('marketime', models.CharField(max_length=50, verbose_name='上市时间')),
                ('insure', models.CharField(blank=True, max_length=100, verbose_name='保修信息')),
            ],
            options={
                'verbose_name': '汽车信息',
                'verbose_name_plural': '汽车信息',
                'unique_together': {('brand', 'carname')},
            },
        ),
        migrations.CreateModel(
            name='CarInformationFiveMonth',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('brand', models.CharField(max_length=100, verbose_name='品牌')),
                ('carname', models.CharField(max_length=100, verbose_name='汽车名称')),
                ('carimg', models.URLField(max_length=255, verbose_name='汽车图片链接')),
                ('salevolume', models.IntegerField(verbose_name='销售量')),
                ('price', models.CharField(max_length=100, verbose_name='价格')),
                ('manufacturer', models.CharField(max_length=100, verbose_name='制造商')),
                ('carmodel', models.CharField(max_length=50, verbose_name='车型')),
                ('energytype', models.CharField(max_length=50, verbose_name='能源类型')),
                ('marketime', models.CharField(max_length=50, verbose_name='上市时间')),
                ('insure', models.CharField(blank=True, max_length=100, verbose_name='保修信息')),
            ],
            options={
                'verbose_name': '汽车信息',
                'verbose_name_plural': '汽车信息',
                'unique_together': {('brand', 'carname')},
            },
        ),
        migrations.CreateModel(
            name='CarInformationFourMonth',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('brand', models.CharField(max_length=100, verbose_name='品牌')),
                ('carname', models.CharField(max_length=100, verbose_name='汽车名称')),
                ('carimg', models.URLField(max_length=255, verbose_name='汽车图片链接')),
                ('salevolume', models.IntegerField(verbose_name='销售量')),
                ('price', models.CharField(max_length=100, verbose_name='价格')),
                ('manufacturer', models.CharField(max_length=100, verbose_name='制造商')),
                ('carmodel', models.CharField(max_length=50, verbose_name='车型')),
                ('energytype', models.CharField(max_length=50, verbose_name='能源类型')),
                ('marketime', models.CharField(max_length=50, verbose_name='上市时间')),
                ('insure', models.CharField(blank=True, max_length=100, verbose_name='保修信息')),
            ],
            options={
                'verbose_name': '汽车信息',
                'verbose_name_plural': '汽车信息',
                'unique_together': {('brand', 'carname')},
            },
        ),
        migrations.CreateModel(
            name='CarInformationGuangzhou',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('brand', models.CharField(max_length=100, verbose_name='品牌')),
                ('carname', models.CharField(max_length=100, verbose_name='汽车名称')),
                ('carimg', models.URLField(max_length=255, verbose_name='汽车图片链接')),
                ('salevolume', models.IntegerField(verbose_name='销售量')),
                ('price', models.CharField(max_length=100, verbose_name='价格')),
                ('manufacturer', models.CharField(max_length=100, verbose_name='制造商')),
                ('carmodel', models.CharField(max_length=50, verbose_name='车型')),
                ('energytype', models.CharField(max_length=50, verbose_name='能源类型')),
                ('marketime', models.CharField(max_length=50, verbose_name='上市时间')),
                ('insure', models.CharField(blank=True, max_length=100, verbose_name='保修信息')),
            ],
            options={
                'verbose_name': '汽车信息',
                'verbose_name_plural': '汽车信息',
                'unique_together': {('brand', 'carname')},
            },
        ),
        migrations.CreateModel(
            name='CarInformationHangzhou',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('brand', models.CharField(max_length=100, verbose_name='品牌')),
                ('carname', models.CharField(max_length=100, verbose_name='汽车名称')),
                ('carimg', models.URLField(max_length=255, verbose_name='汽车图片链接')),
                ('salevolume', models.IntegerField(verbose_name='销售量')),
                ('price', models.CharField(max_length=100, verbose_name='价格')),
                ('manufacturer', models.CharField(max_length=100, verbose_name='制造商')),
                ('carmodel', models.CharField(max_length=50, verbose_name='车型')),
                ('energytype', models.CharField(max_length=50, verbose_name='能源类型')),
                ('marketime', models.CharField(max_length=50, verbose_name='上市时间')),
                ('insure', models.CharField(blank=True, max_length=100, verbose_name='保修信息')),
            ],
            options={
                'verbose_name': '汽车信息',
                'verbose_name_plural': '汽车信息',
                'unique_together': {('brand', 'carname')},
            },
        ),
        migrations.CreateModel(
            name='CarInformationNanchang',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('brand', models.CharField(max_length=100, verbose_name='品牌')),
                ('carname', models.CharField(max_length=100, verbose_name='汽车名称')),
                ('carimg', models.URLField(max_length=255, verbose_name='汽车图片链接')),
                ('salevolume', models.IntegerField(verbose_name='销售量')),
                ('price', models.CharField(max_length=100, verbose_name='价格')),
                ('manufacturer', models.CharField(max_length=100, verbose_name='制造商')),
                ('carmodel', models.CharField(max_length=50, verbose_name='车型')),
                ('energytype', models.CharField(max_length=50, verbose_name='能源类型')),
                ('marketime', models.CharField(max_length=50, verbose_name='上市时间')),
                ('insure', models.CharField(blank=True, max_length=100, verbose_name='保修信息')),
            ],
            options={
                'verbose_name': '汽车信息',
                'verbose_name_plural': '汽车信息',
                'unique_together': {('brand', 'carname')},
            },
        ),
        migrations.CreateModel(
            name='CarInformationNanjing',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('brand', models.CharField(max_length=100, verbose_name='品牌')),
                ('carname', models.CharField(max_length=100, verbose_name='汽车名称')),
                ('carimg', models.URLField(max_length=255, verbose_name='汽车图片链接')),
                ('salevolume', models.IntegerField(verbose_name='销售量')),
                ('price', models.CharField(max_length=100, verbose_name='价格')),
                ('manufacturer', models.CharField(max_length=100, verbose_name='制造商')),
                ('carmodel', models.CharField(max_length=50, verbose_name='车型')),
                ('energytype', models.CharField(max_length=50, verbose_name='能源类型')),
                ('marketime', models.CharField(max_length=50, verbose_name='上市时间')),
                ('insure', models.CharField(blank=True, max_length=100, verbose_name='保修信息')),
            ],
            options={
                'verbose_name': '汽车信息',
                'verbose_name_plural': '汽车信息',
                'unique_together': {('brand', 'carname')},
            },
        ),
        migrations.CreateModel(
            name='CarInformationOneMonth',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('brand', models.CharField(max_length=100, verbose_name='品牌')),
                ('carname', models.CharField(max_length=100, verbose_name='汽车名称')),
                ('carimg', models.URLField(max_length=255, verbose_name='汽车图片链接')),
                ('salevolume', models.IntegerField(verbose_name='销售量')),
                ('price', models.CharField(max_length=100, verbose_name='价格')),
                ('manufacturer', models.CharField(max_length=100, verbose_name='制造商')),
                ('carmodel', models.CharField(max_length=50, verbose_name='车型')),
                ('energytype', models.CharField(max_length=50, verbose_name='能源类型')),
                ('marketime', models.CharField(max_length=50, verbose_name='上市时间')),
                ('insure', models.CharField(blank=True, max_length=100, verbose_name='保修信息')),
            ],
            options={
                'verbose_name': '汽车信息',
                'verbose_name_plural': '汽车信息',
                'unique_together': {('brand', 'carname')},
            },
        ),
        migrations.CreateModel(
            name='CarInformationShanghai',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('brand', models.CharField(max_length=100, verbose_name='品牌')),
                ('carname', models.CharField(max_length=100, verbose_name='汽车名称')),
                ('carimg', models.URLField(max_length=255, verbose_name='汽车图片链接')),
                ('salevolume', models.IntegerField(verbose_name='销售量')),
                ('price', models.CharField(max_length=100, verbose_name='价格')),
                ('manufacturer', models.CharField(max_length=100, verbose_name='制造商')),
                ('carmodel', models.CharField(max_length=50, verbose_name='车型')),
                ('energytype', models.CharField(max_length=50, verbose_name='能源类型')),
                ('marketime', models.CharField(max_length=50, verbose_name='上市时间')),
                ('insure', models.CharField(blank=True, max_length=100, verbose_name='保修信息')),
            ],
            options={
                'verbose_name': '汽车信息',
                'verbose_name_plural': '汽车信息',
                'unique_together': {('brand', 'carname')},
            },
        ),
        migrations.CreateModel(
            name='CarInformationShenzhen',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('brand', models.CharField(max_length=100, verbose_name='品牌')),
                ('carname', models.CharField(max_length=100, verbose_name='汽车名称')),
                ('carimg', models.URLField(max_length=255, verbose_name='汽车图片链接')),
                ('salevolume', models.IntegerField(verbose_name='销售量')),
                ('price', models.CharField(max_length=100, verbose_name='价格')),
                ('manufacturer', models.CharField(max_length=100, verbose_name='制造商')),
                ('carmodel', models.CharField(max_length=50, verbose_name='车型')),
                ('energytype', models.CharField(max_length=50, verbose_name='能源类型')),
                ('marketime', models.CharField(max_length=50, verbose_name='上市时间')),
                ('insure', models.CharField(blank=True, max_length=100, verbose_name='保修信息')),
            ],
            options={
                'verbose_name': '汽车信息',
                'verbose_name_plural': '汽车信息',
                'unique_together': {('brand', 'carname')},
            },
        ),
        migrations.CreateModel(
            name='CarInformationSuzhou',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('brand', models.CharField(max_length=100, verbose_name='品牌')),
                ('carname', models.CharField(max_length=100, verbose_name='汽车名称')),
                ('carimg', models.URLField(max_length=255, verbose_name='汽车图片链接')),
                ('salevolume', models.IntegerField(verbose_name='销售量')),
                ('price', models.CharField(max_length=100, verbose_name='价格')),
                ('manufacturer', models.CharField(max_length=100, verbose_name='制造商')),
                ('carmodel', models.CharField(max_length=50, verbose_name='车型')),
                ('energytype', models.CharField(max_length=50, verbose_name='能源类型')),
                ('marketime', models.CharField(max_length=50, verbose_name='上市时间')),
                ('insure', models.CharField(blank=True, max_length=100, verbose_name='保修信息')),
            ],
            options={
                'verbose_name': '汽车信息',
                'verbose_name_plural': '汽车信息',
                'unique_together': {('brand', 'carname')},
            },
        ),
        migrations.CreateModel(
            name='CarInformationThreeMonth',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('brand', models.CharField(max_length=100, verbose_name='品牌')),
                ('carname', models.CharField(max_length=100, verbose_name='汽车名称')),
                ('carimg', models.URLField(max_length=255, verbose_name='汽车图片链接')),
                ('salevolume', models.IntegerField(verbose_name='销售量')),
                ('price', models.CharField(max_length=100, verbose_name='价格')),
                ('manufacturer', models.CharField(max_length=100, verbose_name='制造商')),
                ('carmodel', models.CharField(max_length=50, verbose_name='车型')),
                ('energytype', models.CharField(max_length=50, verbose_name='能源类型')),
                ('marketime', models.CharField(max_length=50, verbose_name='上市时间')),
                ('insure', models.CharField(blank=True, max_length=100, verbose_name='保修信息')),
            ],
            options={
                'verbose_name': '汽车信息',
                'verbose_name_plural': '汽车信息',
                'unique_together': {('brand', 'carname')},
            },
        ),
        migrations.CreateModel(
            name='CarInformationTianjin',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('brand', models.CharField(max_length=100, verbose_name='品牌')),
                ('carname', models.CharField(max_length=100, verbose_name='汽车名称')),
                ('carimg', models.URLField(max_length=255, verbose_name='汽车图片链接')),
                ('salevolume', models.IntegerField(verbose_name='销售量')),
                ('price', models.CharField(max_length=100, verbose_name='价格')),
                ('manufacturer', models.CharField(max_length=100, verbose_name='制造商')),
                ('carmodel', models.CharField(max_length=50, verbose_name='车型')),
                ('energytype', models.CharField(max_length=50, verbose_name='能源类型')),
                ('marketime', models.CharField(max_length=50, verbose_name='上市时间')),
                ('insure', models.CharField(blank=True, max_length=100, verbose_name='保修信息')),
            ],
            options={
                'verbose_name': '汽车信息',
                'verbose_name_plural': '汽车信息',
                'unique_together': {('brand', 'carname')},
            },
        ),
        migrations.CreateModel(
            name='CarInformationTwoMonth',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('brand', models.CharField(max_length=100, verbose_name='品牌')),
                ('carname', models.CharField(max_length=100, verbose_name='汽车名称')),
                ('carimg', models.URLField(max_length=255, verbose_name='汽车图片链接')),
                ('salevolume', models.IntegerField(verbose_name='销售量')),
                ('price', models.CharField(max_length=100, verbose_name='价格')),
                ('manufacturer', models.CharField(max_length=100, verbose_name='制造商')),
                ('carmodel', models.CharField(max_length=50, verbose_name='车型')),
                ('energytype', models.CharField(max_length=50, verbose_name='能源类型')),
                ('marketime', models.CharField(max_length=50, verbose_name='上市时间')),
                ('insure', models.CharField(blank=True, max_length=100, verbose_name='保修信息')),
            ],
            options={
                'verbose_name': '汽车信息',
                'verbose_name_plural': '汽车信息',
                'unique_together': {('brand', 'carname')},
            },
        ),
        migrations.CreateModel(
            name='CarInformationWuhan',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('brand', models.CharField(max_length=100, verbose_name='品牌')),
                ('carname', models.CharField(max_length=100, verbose_name='汽车名称')),
                ('carimg', models.URLField(max_length=255, verbose_name='汽车图片链接')),
                ('salevolume', models.IntegerField(verbose_name='销售量')),
                ('price', models.CharField(max_length=100, verbose_name='价格')),
                ('manufacturer', models.CharField(max_length=100, verbose_name='制造商')),
                ('carmodel', models.CharField(max_length=50, verbose_name='车型')),
                ('energytype', models.CharField(max_length=50, verbose_name='能源类型')),
                ('marketime', models.CharField(max_length=50, verbose_name='上市时间')),
                ('insure', models.CharField(blank=True, max_length=100, verbose_name='保修信息')),
            ],
            options={
                'verbose_name': '汽车信息',
                'verbose_name_plural': '汽车信息',
                'unique_together': {('brand', 'carname')},
            },
        ),
        migrations.CreateModel(
            name='CarInformationXian',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('brand', models.CharField(max_length=100, verbose_name='品牌')),
                ('carname', models.CharField(max_length=100, verbose_name='汽车名称')),
                ('carimg', models.URLField(max_length=255, verbose_name='汽车图片链接')),
                ('salevolume', models.IntegerField(verbose_name='销售量')),
                ('price', models.CharField(max_length=100, verbose_name='价格')),
                ('manufacturer', models.CharField(max_length=100, verbose_name='制造商')),
                ('carmodel', models.CharField(max_length=50, verbose_name='车型')),
                ('energytype', models.CharField(max_length=50, verbose_name='能源类型')),
                ('marketime', models.CharField(max_length=50, verbose_name='上市时间')),
                ('insure', models.CharField(blank=True, max_length=100, verbose_name='保修信息')),
            ],
            options={
                'verbose_name': '汽车信息',
                'verbose_name_plural': '汽车信息',
                'unique_together': {('brand', 'carname')},
            },
        ),
        migrations.CreateModel(
            name='SpiderCarComment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='主键ID')),
                ('series_id', models.CharField(default='', max_length=50, verbose_name='汽车系列ID')),
                ('carname', models.CharField(default='', max_length=255, verbose_name='汽车名称')),
                ('username', models.CharField(default='', max_length=255, verbose_name='评论用户名')),
                ('user_profile_link', models.CharField(default='', max_length=500, verbose_name='用户主页链接')),
                ('content', models.TextField(default='', verbose_name='评论内容')),
                ('timestamp', models.CharField(default='', max_length=100, verbose_name='评论时间')),
                ('comments', models.CharField(default='0', max_length=10000, verbose_name='评论数')),
                ('likes', models.CharField(default='0', max_length=50, verbose_name='点赞数')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='入库时间')),
            ],
            options={
                'verbose_name': '爬虫-汽车评论',
                'verbose_name_plural': '爬虫-汽车评论',
            },
        ),
        migrations.DeleteModel(
            name='SpiderComment',
        ),
    ]
